### ISSUE TITLE
冒昧开个issue问个验证码相关的问题

### ISSUE THREAD

**Issue by towelong** [gadfly3173/gadfly3173#1]
> 没找到你的邮箱跟其它的联系方式
想请教一个，LinCMS的验证码是怎么做的

**Comment by gadfly3173** [comment]
> 邮箱的话看一下我的git提交记录不就有了么？

验证码的生成是根据网上搜集来的各种验证码图片的生成方法改进来的，前后端传输的格式则是参考了lin cms koa的写法，保证一致性。看一下 [TaleLin/lin-cms-spring-boot/pull/258/files](https://github.com/TaleLin/lin-cms-spring-boot/pull/258/commits) 就能明白吧

**Comment by towelong** [comment]
> > 邮箱的话看一下我的git提交记录不就有了么？
> 
> 验证码的生成是根据网上搜集来的各种验证码图片的生成方法改进来的，前后端传输的格式则是参考了lin cms koa的写法，保证一致性。看一下 [TaleLin/lin-cms-spring-boot/pull/258/files](https://github.com/TaleLin/lin-cms-spring-boot/pull/258/commits) 就能明白吧

我大致看了的，就是前后端分离，如何校验这个验证码？
这一块没看太懂，我大致只看到了好像是通过某种加密算法，把验证码算出来，然后来进行核对？是这样吗

**Comment by gadfly3173** [comment]
java看得比较晕的话可以看一下koa版的代码，目前表现是一致的。将过期时间与验证码拼接成json，通过aes256加密生成tag，tag与图片一起传输到前端；前端提交时将tag和输入的验证码一起发送到后端，后端对tag进行解密、校验时间，与输入的验证码进行比对即可判断。

**Comment by gadfly3173** [comment]
我发布的新pr则是提供了另一个实现，将验证码与过期时间存储在session，通过session进行校验。这样可以在不设置黑名单的情况下防止验证码被重复使用

**Comment by towelong** [comment]
> java看得比较晕的话可以看一下koa版的代码，目前表现是一致的。将过期时间与验证码拼接成json，通过aes256加密生成tag，tag与图片一起传输到前端；前端提交时将tag和输入的验证码一起发送到后端，后端对tag进行解密、校验时间，与输入的验证码进行比对即可判断。

那验证码是存储在了Java内存中吗？就是一般我看别人做验证码都是需要用到Redis，所以我很好奇如何保证两个传入的验证码是否相同

**Comment by gadfly3173** [comment]
tag里存储的就是验证码的四位字符和过期时间呀，仔细看看这段 https://github.com/TaleLin/lin-cms-spring-boot/blob/faccb4b9eb4eca36806904437cb0309d048a1721/src/main/java/io/github/talelin/latticy/common/util/CaptchaUtil.java#L155-L165

**Comment by gadfly3173** [comment]
MAPPER就是jackson的处理对象，用来将BO转为JSON，以及转回BO

**Comment by gadfly3173** [comment]
> > java看得比较晕的话可以看一下koa版的代码，目前表现是一致的。将过期时间与验证码拼接成json，通过aes256加密生成tag，tag与图片一起传输到前端；前端提交时将tag和输入的验证码一起发送到后端，后端对tag进行解密、校验时间，与输入的验证码进行比对即可判断。
> 
> 那验证码是存储在了Java内存中吗？就是一般我看别人做验证码都是需要用到Redis，所以我很好奇如何保证两个传入的验证码是否相同

redis不是必须用到的，如果你本身项目只用session，那么用session解决也是可以的。redis最大的便利之处是不用自己处理过期时间与黑名单

**Comment by towelong** [comment]
> > > java看得比较晕的话可以看一下koa版的代码，目前表现是一致的。将过期时间与验证码拼接成json，通过aes256加密生成tag，tag与图片一起传输到前端；前端提交时将tag和输入的验证码一起发送到后端，后端对tag进行解密、校验时间，与输入的验证码进行比对即可判断。
> > 
> > 
> > 那验证码是存储在了Java内存中吗？就是一般我看别人做验证码都是需要用到Redis，所以我很好奇如何保证两个传入的验证码是否相同
> 
> redis不是必须用到的，如果你本身项目只用session，那么用session解决也是可以的。redis最大的便利之处是不用自己处理过期时间与黑名单

前后端分离的话一般没有用到session，大致是明白了，我再去看看koa的代码

**Comment by towelong** [comment]
感谢解答

**Comment by gadfly3173** [comment]
分离也是可以用session的，用不用session对前端都是几乎无感的，XMLHttpRequest开启withCredentials属性就可以了

**Comment by gadfly3173** [comment]
典型的比如阿里云，前端react，但是还是大量使用session

**Comment by towelong** [comment]
> 典型的比如阿里云，前端react，但是还是大量使用session

能否加个微信，互相学习一下，不方便暴露的话，可以直接加我，就是我github 的id

**Comment by towelong** [comment]
> > 典型的比如阿里云，前端react，但是还是大量使用session
> 
> 能否加个微信，互相学习一下，不方便透露的话，可以直接加我，就是我github 的id
